(source gnu)
(source melpa-stable)
(source marmalade)
(source org)

(depends-on "elscreen")
(depends-on "init-loader")
(depends-on "mozc")
(depends-on "auto-install")
(depends-on "helm-core")
(depends-on "helm")
(depends-on "multiple-cursors")
;;(depends-on "elscreen")
;;(depends-on "elscreen")
;;(depends-on "elscreen")
;;(depends-on "elscreen")
