(source gnu)
(source melpa)
(source marmalade)
(source org)


(depends-on "elscreen")
(depends-on "init-loader")
(depends-on "mozc" :git "git@github.com:emacsmirror/mozc.git")
(depends-on "helm-core")
(depends-on "helm")
(depends-on "multiple-cursors")
(depends-on "php-mode")
(depands-on "open-junk-file")
;;(depends-on "elscreen")
;;(depends-on "elscreen")
;;(depends-on "elscreen")
